### ISSUE TITLE
"InvalidInstanceId" error when calling the SendCommand operation (AWSDevOpsSimplifiedCloud9BootstrapInstanceLambda)

### ISSUE THREAD

**Issue by EricBzr** [PacktPublishing/AWS-DevOps-Simplified#15]
Each attempt at deploying the Cloud9 IDE using the cloud9-ide.yaml (linked in Chapter 3) results in a rollback caused by the error mentioned in the title. The exact failure reason as pulled from the stack cloudwatch group logs is shown below

`botocore.errorfactory.InvalidInstanceId: An error occurred (InvalidInstanceId) when calling the SendCommand operation: Instances [[i-0b964162541ce7df0]] not in a valid state for account 111122223333
`

I did make sure to deploy the stack in the eu-central-1 region as suggested in the text. I even enabled some debug output in the yaml file which kept reflecting that the booted t3 instance is in the "running" state before the ssm command portion of the lambda function code runs. Not sure what else could be jinxing the ssm command or the lambda code from completing.

**Comment by rotbird** [comment]
same here - @EricBzr did you find a solution for that?

**Comment by akskap** [comment]
Hi @EricBzr & @rotbird: I am the author of AWS DevOps Simplified. Apologies that this Github issue did not get timely attention or feedback. I have made sure that I am notified about any future issues, as and when they are raised.

_Issue description:_

The issue you've highlighted seems to stem from the changes rolled out to AWS Systems Manager SSM agent. As part of the referenced pull request, I have made some additions to the CloudFormation template for the Cloud9 IDE. Kindly let me know if you still face any issues with the deployment.

- In order to reproduce the error, and dig deeper into the underlying cause, I modified deployment configuration for the CloudFormation template (in web console) to 'retain' all resources in the same state, when the error occurs.
- Next, I logged into the EC2 instance using AWS Systems Manager Session Manager
- Checking the logs of the SSM Agent surfaced problems around increased exponential backoff time, where the agent would try connecting to the service control plane only after 40-50 minutes (previously, this "wait time" used to be substantially low)
- This means that the EC2 instance until that point of time cannot be managed via SSM to deploy the Document, using the Run command. This is what introduces the error: `Instances [[i-XYZ]] not in a valid state for account XYZ`.
- Technically, resuming the deployment of the failed CloudFormation stack after the time lapse, would allow the SSM Document to be deployed successfully.
- To work around this new SSM Agent behaviour, I've made changes to the Lambda bootstrap function, which stops the EC2 instance, and starts it again, after the new IAM Instance Profile has been attached.
- This makes sure that the SSM Agent has the EC2 node registered again, and can proceed with the Document deployment, without having to wait any longer, or requiring any manual intervention from the end user.
